import type { MapComponent } from '../types';

// The reference (generic) CPU: 24 components. Numbers are typical ranges with their scope.
const C = (c: MapComponent) => c;
const DESK = 'desktop/laptop CPUs, 2020s';

export const CPU_COMPONENTS: MapComponent[] = [
  // ================================================================= CPU (24)
  C({ id: 'cpu.core', world: 'cpu', kind: 'cpu', tech: 'CPU core', friendly: 'One worker', hover: { b: 'A complete processor that runs one stream of instructions (two with SMT).', i: 'An out-of-order superscalar pipeline with private L1/L2 caches; SMT adds a second hardware thread.' }, analogy: 'Like one chef with a private kitchen.', key: { value: '~3–6 GHz · 4–8 instructions/cycle peak', scope: DESK }, why: 'Everything your program does happens inside one; faster cores finish single-threaded work sooner.', teaser: { b: 'The worker that runs your program.', i: 'Front end, out-of-order engine, execution units, private caches.' }, vendor: { amd: 'core (Zen)', intel: 'P-core / E-core', apple: 'P-core / E-core', arm: 'Cortex-X / -A core' } }),
  C({ id: 'cpu.frontend', world: 'cpu', kind: 'cpu', tech: 'Front end (fetch)', friendly: 'Instruction fetcher', hover: { b: 'Grabs the next instructions of your program.', i: 'Fetches instruction bytes from L1I each cycle, steered by the branch predictor.' }, analogy: 'Like reading the next lines of a recipe.', key: { value: '~32 B of instructions per cycle is common (approx.)', scope: DESK }, why: 'If the front end stalls, the whole core runs dry no matter how many execution units it has.', teaser: 'Where every instruction enters the core.' }),
  C({ id: 'cpu.bpred', world: 'cpu', kind: 'cpu', tech: 'Branch predictor', friendly: 'The guesser', hover: { b: 'Guesses which way each "if" will go, so the core never waits to find out.', i: 'Predicts branch direction and target ahead of fetch; designs are mostly unpublished.' }, analogy: 'Like guessing the next turn on a familiar drive.', key: { value: 'a misprediction costs ~10–20 cycles', scope: DESK }, why: 'About 1 in 5–6 instructions is a branch in typical code; guessing wrong throws away work.', teaser: 'Guessing the future, correctly most of the time.' }),
  C({ id: 'cpu.l1i', world: 'cpu', kind: 'mem', tech: 'L1 instruction cache', friendly: 'Instruction shelf', hover: { b: 'Keeps the program’s next instructions close by.', i: 'Private per core, read by the front end every cycle.' }, analogy: 'Like keeping the open recipe on the counter.', key: { value: '32–64 KB (Apple P-cores: larger)', scope: DESK }, why: 'Without it, every fetch would wait on slower caches.', teaser: 'Instructions need caching too.' }),
  C({ id: 'cpu.decode', world: 'cpu', kind: 'cpu', tech: 'Decoder (+ µop cache)', friendly: 'Translator', hover: { b: 'Turns instruction bytes into simple steps the core can run.', i: 'Decodes ISA instructions into micro-ops; a µop/op cache skips decode for hot code.' }, analogy: 'Like translating a recipe into simple kitchen steps.', key: { value: '4–8 instructions decoded per cycle', scope: DESK }, why: 'Decode width caps how many instructions can enter the core each cycle.', teaser: 'x86, ARM, RISC‑V: different languages, same idea.', vendor: { amd: 'decode + Op Cache', intel: 'decoders + DSB (µop cache)', apple: 'decode', arm: 'decode + MOP cache' } }),
  C({ id: 'cpu.rename', world: 'cpu', kind: 'cpu', tech: 'Register rename / allocate', friendly: 'Name tagger', hover: { b: 'Gives each result a fresh storage slot so independent work doesn’t wait.', i: 'Maps architectural registers to physical registers, removing false (WAR/WAW) dependences.' }, analogy: 'Like giving each order its own numbered tray.', key: { value: '~4–8 instructions renamed per cycle', scope: DESK }, why: 'Without renaming, reusing a register name would force needless waiting.', teaser: 'Removing fake dependences.' }),
  C({ id: 'cpu.rob', world: 'cpu', kind: 'cpu', tech: 'Reorder buffer (ROB)', friendly: 'Out-of-order bookkeeping', hover: { b: 'Tracks work done out of order and puts results back in program order.', i: 'In-flight micro-ops retire in program order from the ROB; its size sets the out-of-order window.' }, analogy: 'Like a ticket rail that serves orders in sequence.', key: { value: '~200–600 entries', scope: DESK }, why: 'Its size decides how far the core can look ahead to hide a slow load.', teaser: 'Doing things out of order without anyone noticing.', vendor: { amd: 'retire queue', intel: 'ROB', apple: 'ROB (size not published)' } }),
  C({ id: 'cpu.sched', world: 'cpu', kind: 'cpu', tech: 'Schedulers', friendly: 'The dispatcher', hover: { b: 'Sends each step to a free worker as soon as its inputs are ready.', i: 'Reservation stations / issue queues wake micro-ops when operands are ready and pick ones to issue.' }, analogy: 'Like a head chef assigning dishes to free cooks.', key: { value: 'several queues, issuing ~6–12 ops/cycle (approx.)', scope: DESK }, why: 'They find the parallelism inside your single thread.', teaser: 'Who runs next, and when.', vendor: { amd: 'schedulers', intel: 'reservation stations', arm: 'issue queues' } }),
  C({ id: 'cpu.prf', world: 'cpu', kind: 'mem', tech: 'Physical register file', friendly: 'The core’s notepad', hover: { b: 'The fastest storage of all: a few hundred slots inside the core.', i: 'Holds renamed register values; separate integer and vector/FP files.' }, analogy: 'Like a cook’s scratch pad on the counter.', key: { value: '~200–300 entries per type (approx.)', scope: DESK }, why: 'Every instruction reads and writes it; it must answer every cycle.', teaser: 'Storage that answers in a single cycle.' }),
  C({ id: 'cpu.alu', world: 'cpu', kind: 'gpu', tech: 'Integer ALUs', friendly: 'Integer math', hover: { b: 'Adds, compares and shifts whole numbers.', i: 'Single-cycle integer ops plus branch resolution; results forward to dependents.' }, analogy: 'Like a calculator for whole numbers.', key: { value: '3–6 per core', scope: DESK }, why: 'Most instructions in everyday code are integer work.', teaser: 'Where whole-number math happens.' }),
  C({ id: 'cpu.lsu', world: 'cpu', kind: 'mem', tech: 'Load/store unit', friendly: 'Memory doorway', hover: { b: 'Reads data from memory into the core and writes it back.', i: 'AGUs compute addresses; load/store queues and the store buffer track memory ops in flight.' }, analogy: 'Like the pass-through window to the pantry.', key: { value: '~2–3 loads + 1–2 stores per cycle', scope: DESK }, why: 'Every memory access passes here; its queues let loads run ahead of older stores.', teaser: 'Every read and write passes through here.' }),
  C({ id: 'cpu.fpsimd', world: 'cpu', kind: 'gpu', tech: 'FP / SIMD units', friendly: 'Batch math', hover: { b: 'Math on decimal numbers, often many at once with one instruction.', i: 'Floating-point and vector pipes: SSE/AVX/AVX-512 on x86, NEON/SVE on Arm.' }, analogy: 'Like a cookie cutter that stamps 8 at once.', key: { value: '128–512-bit vectors · 2–4 FP pipes', scope: DESK }, why: 'For number crunching, vectors multiply throughput by 4–16× per instruction.', teaser: 'A tiny taste of GPU-style math inside a CPU.', vendor: { intel: 'AVX2 / AVX-512 / AMX', amd: 'AVX2 / AVX-512', apple: 'NEON (+ AMX coprocessor)', arm: 'NEON / SVE' } }),
  C({ id: 'cpu.l1d', world: 'cpu', kind: 'mem', tech: 'L1 data cache', friendly: 'The closest shelf', hover: { b: 'A small, very fast store of recently used data right next to the core.', i: 'Private, set-associative, 64 B lines; the first place every load looks.' }, analogy: 'Like the spice rack within arm’s reach.', key: { value: '32–64 KB · ~4–5 cycles (Apple P-cores: 128 KB)', scope: DESK }, why: 'Without it, every load would wait hundreds of cycles for DRAM instead of ~4.', teaser: { b: 'The few KB that do most of the work.', i: 'Sets, ways and tags: how an address finds its byte.' }, sandbox: { label: 'Open in cache simulator', href: '#/lab/cache' }, vendor: { amd: 'L1 data cache', intel: 'L1D / DCU', apple: 'L1D', arm: 'L1 data cache' } }),
  C({ id: 'cpu.tlb', world: 'cpu', kind: 'mem', tech: 'TLBs + page walker', friendly: 'Address translator', hover: { b: 'Turns the addresses programs use into real memory locations, fast.', i: 'Caches virtual→physical translations; a miss triggers a page-table walk.' }, analogy: 'Like a cheat-sheet of house numbers to street addresses.', key: { value: 'L1 DTLB ~64–96 · L2 TLB ~1–3K entries · 4 KB pages', scope: DESK }, why: 'Every load needs a translation; walking page tables each time would be ruinous.', teaser: 'Every program thinks it owns all the memory.' }),
  C({ id: 'cpu.l2', world: 'cpu', kind: 'mem', tech: 'L2 cache', friendly: 'The nearby cupboard', hover: { b: 'Bigger and a bit slower than L1. Catches what L1 drops.', i: 'Usually private per core (Apple shares it per cluster); hardware prefetchers live here.' }, analogy: 'Like the cupboard behind you.', key: { value: '0.5–2 MB per core · ~12–16 cycles', scope: DESK }, why: 'It cuts the cost of an L1 miss from ~50 cycles (L3) to ~14.', teaser: 'The second chance before things get slow.', sandbox: { label: 'Open in cache simulator', href: '#/lab/cache' } }),
  C({ id: 'cpu.l3', world: 'cpu', kind: 'mem', tech: 'L3 cache (shared)', friendly: 'The shared pantry', hover: { b: 'A big store shared by all the cores on the chip.', i: 'Last-level cache, split into slices next to the cores; often also tracks coherence.' }, analogy: 'Like the shared pantry for every cook.', key: { value: '~2–4 MB per core · ~40–60 cycles (approx.)', scope: DESK }, why: 'It keeps data shared between cores off the slow trip to DRAM.', teaser: 'Shared by every core.', vendor: { amd: 'L3 (per CCD)', intel: 'LLC (L3)', apple: 'SLC (system level cache)' } }),
  C({ id: 'cpu.interconnect', world: 'cpu', kind: 'mem', tech: 'On-chip interconnect', friendly: 'On-chip roads', hover: { b: 'The wiring that carries data between cores, caches and memory.', i: 'Ring buses in client chips, meshes in servers, chiplet fabrics between dies.' }, analogy: 'Like the corridors between kitchen stations.', key: { value: 'ring (client) · mesh (server) · fabric (chiplets)', scope: DESK }, why: 'Every L3 access and every core-to-core message rides on it.', teaser: 'Rings, meshes and chiplets.', vendor: { amd: 'Infinity Fabric', intel: 'ring / mesh', apple: 'fabric', arm: 'CMN mesh' } }),
  C({ id: 'cpu.coherence', world: 'cpu', kind: 'mem', tech: 'Snoop filter / directory', friendly: 'Keeping copies in sync', dossierTitle: 'Cache coherence (MESI/MOESI)', hover: { b: 'Makes sure two cores never see different values for the same data.', i: 'Tracks which cores hold each line; enforces a MESI/MOESI-family protocol.' }, analogy: 'Like a whiteboard listing who borrowed which book.', key: { value: 'tracks state per 64 B line', scope: DESK }, why: 'Without it, multi-threaded code would read stale data.', teaser: 'Why two threads touching neighbouring bytes can be slow.', vendor: { intel: 'snoop filter (CHA)', amd: 'probe filter / directory', arm: 'snoop filter' } }),
  C({ id: 'cpu.memctl', world: 'cpu', kind: 'mem', tech: 'Memory controller', friendly: 'RAM traffic control', hover: { b: 'Schedules every trip out to the RAM sticks.', i: 'Turns cache misses into DRAM commands across channels, ranks and banks.' }, analogy: 'Like the dispatcher for delivery trucks.', key: { value: '2 channels (desktop) · 8–12 (servers)', scope: DESK }, why: 'Its scheduling decides how much of DRAM’s peak bandwidth you actually get.', teaser: 'Turning requests into DRAM commands.', vendor: { intel: 'IMC', amd: 'UMC' } }),
  C({ id: 'cpu.dram', world: 'cpu', kind: 'mem', tech: 'DRAM (DDR5 / LPDDR5)', friendly: 'Main memory (RAM)', hover: { b: 'Gigabytes of storage, but far away: hundreds of cycles per trip.', i: 'DDR5 DIMMs or soldered LPDDR5; ~70–110 ns load latency.' }, analogy: 'Like the warehouse across town.', key: { value: '~70–110 ns · DDR5: 38–51 GB/s per 64-bit channel', scope: DESK }, why: 'Everything that doesn’t fit in cache lives here; the gap to the core is the memory wall.', teaser: 'Huge, cheap, and slow to reach.' }),
  C({ id: 'cpu.pcie', world: 'cpu', kind: 'mem', tech: 'PCIe / I/O', friendly: 'Expansion highway', hover: { b: 'High-speed lanes to graphics cards and SSDs.', i: 'PCIe root complex; Gen5 ≈ 3.94 GB/s per lane per direction after encoding.' }, analogy: 'Like the highway out of town.', key: { value: 'Gen4 ≈ 1.97 · Gen5 ≈ 3.94 GB/s per lane each way', scope: 'PCI-SIG specs' }, why: 'Data headed to a GPU or SSD crosses here, often the slowest link.', teaser: 'Lanes, generations and real bandwidth.' }),
  C({ id: 'cpu.power', world: 'cpu', kind: 'cpu', tech: 'Power and clocks', friendly: 'Why chips get hot', hover: { b: 'Every switch flip costs energy; this part decides clocks and voltages.', i: 'VRMs feed the package; on-die power management does DVFS and boost.' }, analogy: 'Like a thermostat and fuse box together.', key: { value: '~15–45 W laptops · ~65–250 W desktops', scope: DESK }, why: 'Power and heat, not transistor count, now cap clock speeds.', teaser: 'Why clock speeds stopped rising around 2005.' }),
  C({ id: 'cpu.nvme', world: 'cpu', kind: 'mem', tech: 'NVMe SSD', friendly: 'Storage drive', hover: { b: 'Where files live when the power is off.', i: 'Flash storage over 4 PCIe lanes; deep queues hide latency.' }, analogy: 'Like the filing cabinet in the basement.', key: { value: 'Gen4 x4 link ≈ 7.9 GB/s · ~tens of µs latency', scope: '2020s NVMe drives' }, why: 'Fast storage is still ~1,000× slower to reach than RAM.', teaser: 'Fast storage, still far away.' }),
  C({ id: 'cpu.numa', world: 'cpu', kind: 'mem', tech: 'Multi-socket / NUMA', friendly: 'Near and far memory', hover: { b: 'On big servers, some memory is closer to some cores.', i: 'Non-uniform memory access: remote-socket memory costs extra latency and bandwidth.' }, analogy: 'Like a second warehouse that’s further away.', key: { value: 'remote memory ~1.3–2× local latency (approx.)', scope: '2–8-socket servers, 2020s' }, why: 'Ignore it and a server program can run much slower than expected.', teaser: 'When "memory" has a location.' }),

];
