import type { MapComponent } from '../types';

// The reference (generic) GPU: 15 components + 3 server-level parts. Typical ranges with scope.
const C = (c: MapComponent) => c;
const GPU = 'datacenter and desktop GPUs, 2020s';

export const GPU_COMPONENTS: MapComponent[] = [
  // ================================================================= GPU (15)
  C({ id: 'gpu.cmdproc', world: 'gpu', kind: 'cpu', tech: 'Command processor + work distributor', friendly: 'Handout desk', hover: { b: 'Reads the work the CPU sent and hands chunks of it to free compute units.', i: 'Parses command streams and distributes thread blocks / workgroups to compute units.' }, analogy: 'Like a foreman handing out jobs.', key: { value: 'one per GPU (plus async queues)', scope: GPU }, why: 'It keeps thousands of lanes fed; a slow handout leaves units idle.', teaser: 'Who decides which unit gets which block.', vendor: { nvidia: 'GigaThread engine', amd: 'Command Processor + ACEs', intel: 'command streamer' } }),
  C({ id: 'gpu.cluster', world: 'gpu', kind: 'gpu', tech: 'Compute cluster', friendly: 'Team of worker units', hover: { b: 'A group of compute units that share some hardware.', i: 'Shares front-end/raster resources among its compute units.' }, analogy: 'Like a floor of a factory.', key: { value: '~4–12 per GPU', scope: GPU }, why: 'It’s how big GPUs are organised and scaled up or down.', teaser: 'How compute units are grouped.', vendor: { nvidia: 'GPC', amd: 'Shader Engine / XCD', intel: 'Render Slice', apple: '—' } }),
  C({ id: 'gpu.cu', world: 'gpu', kind: 'gpu', tech: 'Compute unit', friendly: 'Worker unit', hover: { b: 'A mini-processor that runs many groups of threads at once.', i: 'Schedulers, register file, vector ALUs, matrix units, LD/ST and shared memory/L1.' }, analogy: 'Like a workshop full of identical benches.', key: { value: 'tens to ~150 per GPU (304 on AMD MI300X)', scope: GPU }, why: 'All of a GPU’s math happens here; its resources decide how many threads can be in flight.', teaser: { b: 'Where all the GPU’s work happens.', i: 'Warps, schedulers, register file, lanes, shared memory.' }, vendor: { nvidia: 'SM (streaming multiprocessor)', amd: 'CU / WGP', intel: 'Xe-core', apple: 'GPU core' } }),
  C({ id: 'gpu.warpsched', world: 'gpu', kind: 'cpu', tech: 'Warp/wavefront scheduler + dispatch', friendly: 'Turn-taker', hover: { b: 'Each cycle, picks a group of threads that is ready and lets it run.', i: 'Issues one instruction per cycle from a ready warp/wavefront; switching costs nothing.' }, analogy: 'Like a coach sending in whichever player is ready.', key: { value: 'warp = 32 threads (NVIDIA) · wavefront = 32 or 64 (AMD)', scope: GPU }, why: 'Switching to a ready group is how a GPU hides slow memory.', teaser: 'How a GPU hides waiting.', vendor: { nvidia: 'warp scheduler', amd: 'wave scheduler', intel: 'thread scheduler' } }),
  C({ id: 'gpu.regfile', world: 'gpu', kind: 'mem', tech: 'Register file', friendly: 'Everyone’s notepad', hover: { b: 'Huge: every thread keeps its own values here, so switching groups is free.', i: 'Per-thread registers for all resident warps; its size limits occupancy.' }, analogy: 'Like a locker for every worker so nobody tidies up between shifts.', key: { value: '~128–512 KB per compute unit', scope: GPU }, why: 'Its size decides how many warps can be resident to hide latency.', teaser: 'Why a GPU’s registers outweigh its caches.', vendor: { amd: 'VGPRs (+ AGPRs on CDNA)', nvidia: 'register file' } }),
  C({ id: 'gpu.valu', world: 'gpu', kind: 'gpu', tech: 'Vector ALUs (FP32 / INT32 / FP64)', friendly: 'Math lanes', hover: { b: 'Simple math units. A GPU has thousands.', i: 'One warp instruction drives all lanes in lockstep; FP64 is reduced on consumer GPUs.' }, analogy: 'Like a row of identical calculators pressed at once.', key: { value: '~64–128 FP32 lanes per compute unit', scope: GPU }, why: 'They do all the non-matrix math, from shading to activations.', teaser: 'Thousands of lanes doing simple math together.', vendor: { nvidia: 'CUDA cores', amd: 'stream processors', intel: 'XVE', apple: 'ALUs' } }),
  C({ id: 'gpu.matrix', world: 'gpu', kind: 'gpu', tech: 'Matrix units', friendly: 'Matrix engines', hover: { b: 'Special units that multiply small grids of numbers in one go.', i: 'Matrix-multiply-accumulate on tiles in FP16/BF16/FP8/INT8; most of a modern GPU’s FLOP/s.' }, analogy: 'Like multiplying whole tables at once instead of cell by cell.', key: { value: 'dense BF16 ~100–2,000+ TFLOP/s per GPU', scope: GPU }, why: 'They make AI training and inference possible at today’s scale.', teaser: 'Where AI’s math actually happens.', vendor: { nvidia: 'Tensor Cores', amd: 'Matrix Cores', intel: 'XMX', apple: '— (CPU-side AMX / Neural Engine)' } }),
  C({ id: 'gpu.ldsfu', world: 'gpu', kind: 'mem', tech: 'Load/store + special-function units', friendly: 'Memory doors', hover: { b: 'Fetch data for the lanes, plus a few units for tricky math like square roots.', i: 'LD/ST units issue memory requests; SFUs compute transcendentals (sin, exp, rsqrt).' }, analogy: 'Like runners to the stockroom plus a specialist for hard sums.', key: { value: 'SFUs: a fraction of the lane count', scope: GPU }, why: 'Memory ops and transcendentals run here, so they’re slower than plain math.', teaser: 'Memory requests and special math.' }),
  C({ id: 'gpu.smem', world: 'gpu', kind: 'mem', tech: 'Shared memory / LDS + L1', friendly: 'Team scratchpad', hover: { b: 'A fast scratchpad that threads in the same block share.', i: 'Software-managed SRAM, banked (32 banks of 4 B on NVIDIA), shared with the L1 cache.' }, analogy: 'Like a shared whiteboard for one team.', key: { value: '~64–256 KB per compute unit · ~20–30 cycles', scope: GPU }, why: 'Reusing data from here instead of device memory is the key to fast kernels.', teaser: 'Banks, conflicts and coalescing.', vendor: { nvidia: 'shared memory', amd: 'LDS', intel: 'SLM', apple: 'threadgroup memory' } }),
  C({ id: 'gpu.l2', world: 'gpu', kind: 'mem', tech: 'L2 cache', friendly: 'Shared store', hover: { b: 'A big store in the middle that all compute units share.', i: 'Last on-chip cache before device memory; some GPUs add a further "Infinity Cache".' }, analogy: 'Like the central stockroom.', key: { value: '~4–100 MB per GPU', scope: GPU }, why: 'Every device-memory access passes through it; hits save hundreds of cycles.', teaser: 'The last stop before device memory.' }),
  C({ id: 'gpu.memctl', world: 'gpu', kind: 'mem', tech: 'Memory controllers + PHY', friendly: 'Memory doorway', hover: { b: 'The circuits along the chip’s edge that talk to its memory chips.', i: 'Many narrow controllers; together they set the memory bus width.' }, analogy: 'Like loading bays along a warehouse wall.', key: { value: 'GDDR: 128–512-bit bus · HBM: 4,096–8,192-bit', scope: GPU }, why: 'Bus width × data rate is the GPU’s memory bandwidth.', teaser: 'How wide the memory road is.' }),
  C({ id: 'gpu.devmem', world: 'gpu', kind: 'mem', tech: 'Device memory (GDDR or HBM)', friendly: 'The GPU’s memory', hover: { b: 'The GPU’s own gigabytes: very fast, but hundreds of cycles away.', i: 'GDDR chips on the board, or HBM stacks beside the die on an interposer.' }, analogy: 'Like a warehouse right next to the factory.', key: { value: 'GDDR ~0.3–1.8 TB/s · HBM ~1–8 TB/s per GPU', scope: GPU }, why: 'Most AI workloads are limited by how fast this can be read.', teaser: 'Why GPU memory is 10–100× faster than your RAM.', vendor: { nvidia: 'HBM3/3e or GDDR6X/7', amd: 'HBM3 or GDDR6', intel: 'HBM2e or GDDR6', apple: 'unified LPDDR5' } }),
  C({ id: 'gpu.host_if', world: 'gpu', kind: 'mem', tech: 'Host interface + copy engines', friendly: 'Loading dock', hover: { b: 'Where data arrives from the CPU.', i: 'PCIe endpoint plus DMA copy engines that move data while compute runs.' }, analogy: 'Like the loading dock where trucks arrive.', key: { value: 'PCIe 4.0/5.0 x16 ≈ 32–63 GB/s each way', scope: GPU }, why: 'Copies over PCIe can take longer than the math itself.', teaser: 'Data has to get here first.' }),
  C({ id: 'gpu.links', world: 'gpu', kind: 'mem', tech: 'GPU-to-GPU links + switches', friendly: 'GPU-to-GPU highway', hover: { b: 'A private, very fast road so GPUs can share data directly.', i: 'Point-to-point links plus switch chips for all-to-all traffic inside a node.' }, analogy: 'Like a private corridor between factories.', key: { value: '~0.1–1.8 TB/s per GPU', scope: GPU }, why: 'Large models are split across GPUs; this link sets how fast they can cooperate.', teaser: 'All-to-all inside a server.', vendor: { nvidia: 'NVLink / NVSwitch', amd: 'Infinity Fabric links', intel: 'Xe Link' } }),
  C({ id: 'gpu.gfx', world: 'gpu', kind: 'gpu', tech: 'Graphics fixed-function units', friendly: 'Drawing hardware', hover: { b: 'Units that only draw graphics: textures, triangles and ray tracing.', i: 'Texture units, rasterisers, ROPs and ray-tracing units; reduced or absent on some datacenter GPUs.' }, analogy: 'Like special stencils that only an artist uses.', key: { value: 'present on graphics GPUs · reduced on some AI GPUs', scope: GPU }, why: 'GPUs began as graphics chips; this hardware is why a game can render 100+ frames per second.', teaser: 'GPUs also draw pictures.', vendor: { nvidia: 'TMUs, raster, ROPs, RT cores', amd: 'TMUs, raster, ROPs, Ray Accelerators', intel: 'samplers, RTUs', apple: 'TMUs, RT units' } }),

  // ================================================================= GPU server (3)
  C({ id: 'gpu.node', world: 'gpu', kind: 'gpu', tech: 'Multi-GPU node', friendly: 'Many GPUs in one box', hover: { b: 'One server, several GPUs working on one model.', i: 'GPUs on one board, joined by GPU-to-GPU links and switches.' }, analogy: 'Like several factories on one campus.', key: { value: '4–8 GPUs per node', scope: 'AI servers, 2020s' }, why: 'Today’s largest models don’t fit on one GPU.', teaser: 'Why big models need many GPUs.' }),
  C({ id: 'gpu.nics', world: 'gpu', kind: 'mem', tech: 'NICs + network', friendly: 'Link to other servers', hover: { b: 'Connects this server to thousands of others.', i: 'RDMA network adapters, typically one per GPU in AI servers.' }, analogy: 'Like the railway between campuses.', key: { value: '~200–800 Gb/s per NIC', scope: 'AI servers, 2020s' }, why: 'Training across many servers is limited by this network.', teaser: 'Scaling past one box.' }),
  C({ id: 'gpu.host', world: 'gpu', kind: 'cpu', tech: 'Host CPUs', friendly: 'The CPUs in charge', hover: { b: 'CPUs that run the program and feed the GPUs.', i: 'Launch kernels, run the data pipeline, copy batches over PCIe.' }, analogy: 'Like the office that plans the factory’s work.', key: { value: '1–2 per node', scope: 'AI servers, 2020s' }, why: 'If the host can’t keep up, expensive GPUs sit idle.', teaser: 'The CPU’s job in a GPU server.' }),

];
