import type { Architecture } from './types';
import { GPU_HOPPER } from '../chipmaps';

const S = { ds: 'ds', wp: 'wp', blog: 'blog', luo: 'luo', tnp: 'tnp', tpu: 'tpu', cnc: 'cnc', dgx: 'dgx', cuda: 'cuda' } as const;

export const HOPPER_H100: Architecture = {
  id: 'hopper-h100', world: 'gpu', group: 'GPU families', family: 'NVIDIA', name: 'NVIDIA H100 SXM5 (Hopper)', short: 'Hopper · H100', maker: 'NVIDIA', year: 2022, status: 'ready',
  isa: 'PTX / SASS (CUDA), compute capability 9.0', usedIn: 'AI training and inference in datacenters, usually 8 per DGX/HGX server.',
  tree: GPU_HOPPER, spec: 'h100-sxm',
  sources: [
    { id: S.ds, title: 'NVIDIA H100 Tensor Core GPU datasheet', year: 2022 },
    { id: S.wp, title: 'NVIDIA H100 Tensor Core GPU Architecture whitepaper', year: 2022 },
    { id: S.blog, title: 'NVIDIA Technical Blog, "NVIDIA Hopper Architecture In-Depth"', url: 'https://developer.nvidia.com/blog/nvidia-hopper-architecture-in-depth/', year: 2022 },
    { id: S.luo, title: 'Luo et al., "Dissecting the NVIDIA Hopper Architecture through Microbenchmarking and Multiple Level Analysis" (measured on an H800 PCIe, same GH100 design)', url: 'https://arxiv.org/abs/2501.12084', year: 2025 },
    { id: S.tnp, title: 'The Next Platform, "Deep Dive Into Nvidia’s Hopper GPU Architecture" (SM diagram: 8 LD/ST + 4 SFU per quadrant)', url: 'https://www.nextplatform.com/2022/03/31/deep-dive-into-nvidias-hopper-gpu-architecture/', year: 2022 },
    { id: S.tpu, title: 'TechPowerUp GPU Database, NVIDIA GH100 (2,304 SFUs on the full die)', url: 'https://www.techpowerup.com/gpu-specs/nvidia-gh100.g1011', year: 2022 },
    { id: S.cnc, title: 'Chips and Cheese, "Nvidia’s H100: Funny L2, and Tons of Bandwidth"', url: 'https://chipsandcheese.com/p/nvidias-h100-funny-l2-and-tons-of-bandwidth', year: 2023 },
    { id: S.dgx, title: 'NVIDIA DGX H100 datasheet', year: 2022 },
    { id: S.cuda, title: 'NVIDIA CUDA C++ Programming Guide, compute capability 9.0 limits', year: 2024 },
  ],
  glance: [
    { label: 'GPU', value: 'GH100 · H100 SXM5', src: S.ds },
    { label: 'SMs', value: '132 of 144 enabled', src: S.wp },
    { label: 'FP32', value: '67 TFLOP/s', src: S.ds },
    { label: 'BF16 tensor', value: '989.4 TFLOP/s dense', src: S.ds },
    { label: 'L2', value: '50 MB', src: S.ds },
    { label: 'HBM3', value: '80 GB · 3.35 TB/s', src: S.ds },
  ],
  parts: {
    'gpu.cmdproc': { key: { label: 'Limit', value: '≤ 32 resident blocks per SM', src: S.cuda }, note: 'NVIDIA calls it the GigaThread engine.' },
    'gpu.cluster': { key: { label: 'GPCs', value: '8 on the full GH100 die (9 TPCs × 2 SMs each)', src: S.wp }, note: 'Hopper adds thread-block clusters: blocks in one GPC can share each other’s shared memory.' },
    'gpu.cu': { key: { label: 'SMs', value: '132 of 144 enabled', src: S.wp } },
    'gpu.warpsched': { key: { label: 'Per SM', value: '4 schedulers · warp = 32 threads', src: S.wp } },
    'gpu.regfile': { key: { label: 'Size', value: '64 KB per partition · 256 KB per SM', src: S.wp } },
    'gpu.valu': { key: { label: 'Per partition', value: '32 FP32 · 16 INT32 · 16 FP64', src: S.wp } },
    'gpu.matrix': { key: { label: 'Tensor Cores', value: '4th gen · 4 per SM · BF16 989.4 TFLOP/s dense (GPU)', src: S.ds }, note: 'Adds FP8 with the Transformer Engine: 1,979 TFLOP/s dense FP8.' },
    'gpu.ldsfu': { key: { label: 'Per partition', value: '8 LD/ST · 4 SFU', src: S.tnp } },
    'gpu.smem': { key: { label: 'Size', value: '256 KB L1+shared per SM (≤ 228 KB shared) · ≈ 29 cycles', src: S.luo } },
    'gpu.l2': { key: { label: 'L2', value: '50 MB in two halves · near hit ≈ 258, far ≈ 414 cycles', src: S.luo }, note: 'Reaching the far half of L2 takes about 1.6× longer (measured on H800 PCIe).' },
    'gpu.memctl': { key: { label: 'Bus', value: '10 × 512-bit active (12 on die) = 5,120 bit', src: S.wp } },
    'gpu.devmem': { key: { label: 'HBM3', value: '80 GB · 3.35 TB/s · 5 active stacks of 6 sites', src: S.ds }, note: 'An L2 miss costs ≈ 556–744 cycles in measurements (H800 PCIe).' },
    'gpu.host_if': { key: { label: 'Host link', value: 'PCIe 5.0 x16 · 128 GB/s total', src: S.ds } },
    'gpu.links': { key: { label: 'NVLink 4', value: '18 links · 900 GB/s per GPU', src: S.ds } },
    'gpu.gfx': { note: 'Per NVIDIA’s whitepaper, only two TPCs can run graphics shaders; there are no RT cores or display outputs.' },
    'gpu.node': { key: { label: 'DGX H100', value: '8 × H100 SXM5 · 640 GB HBM3', src: S.dgx } },
    'gpu.nics': { key: { label: 'Network', value: '8 × 400 Gb/s ConnectX-7', src: S.dgx } },
    'gpu.host': { key: { label: 'CPUs', value: '2 × Intel Xeon Platinum 8480C', src: S.dgx } },
  },
  ownParts: [
    {
      id: 'hopper.tma', dossier: 'hopper.tma', extends: 'gpu.smem', world: 'gpu', kind: 'mem', tech: 'Tensor Memory Accelerator (TMA)', friendly: 'Tile mover',
      hover: { b: 'A copier inside each SM that brings whole tiles of data into shared memory in the background.', i: 'Asynchronous bulk copies of tensor tiles between global and shared memory, with address generation in hardware.' },
      analogy: 'Like a forklift that brings a whole pallet while the workers keep working.',
      key: { value: '1 per SM', src: S.wp },
      why: 'It frees threads from address math and lets copying overlap with compute.',
      teaser: 'Hopper’s background copy engine for tiles.',
    },
  ],
  diff: [
    { b: '**Thread-block clusters.** Teams of thread blocks can share each other’s scratchpads.', i: '**Thread-block clusters + distributed shared memory:** blocks in one GPC read/write each other’s shared memory.' },
    { b: '**A tile mover (TMA)** copies whole blocks of data in the background.', i: '**TMA:** asynchronous bulk tensor copies global ↔ shared, address generation in hardware.' },
    { b: '**8-bit math for AI.** The matrix units can use tiny FP8 numbers for double speed.', i: '**FP8 + Transformer Engine:** 1,979 TFLOP/s dense FP8, 2× BF16.' },
    { b: '**Stacked memory on a silicon base.** Memory chips sit right beside the GPU.', i: '**HBM3 on CoWoS:** 5 active stacks, 3.35 TB/s.' },
    { b: '**A split L2.** The far half is slower to reach.', i: '**Two-partition L2:** near ≈ 258 vs far ≈ 414 cycles (measured).' },
    { b: '**Little graphics hardware.** It’s built for AI, not games.', i: '**Reduced graphics:** 2 graphics-capable TPCs, no RT cores, no display outputs.' },
  ],
  choices: [
    { title: 'Why spend so much on matrix units?', text: { b: 'AI is mostly multiplying big grids of numbers, so dedicated matrix hardware pays off most.', i: 'Dense GEMMs dominate training; tensor-core FLOP/s per mm² and per watt far exceed FP32 lanes.' } },
    { title: 'Why HBM instead of GDDR?', text: { b: 'AI needs to read huge amounts of data fast; stacked memory gives far more bandwidth.', i: 'HBM’s 5,120-bit interface reaches 3.35 TB/s at lower energy per bit, at higher cost and capacity limits.' } },
    { title: 'Why drop graphics?', text: { b: 'Space used for drawing hardware is better spent on AI math in a datacenter chip.', i: 'RT cores, display and most raster hardware give way to tensor cores and larger L1/shared memory.' } },
  ],
  timeline: [
    { year: '2016', name: 'Pascal (P100)', note: 'First NVIDIA datacenter GPU with HBM2 and NVLink.' },
    { year: '2017', name: 'Volta (V100)', note: 'First Tensor Cores.' },
    { year: '2020', name: 'Ampere (A100)', note: 'TF32, structured sparsity, 40 MB L2.' },
    { year: '2022', name: 'Hopper (H100)', note: 'FP8, TMA, thread-block clusters, HBM3.', current: true },
    { year: '2024', name: 'Blackwell', note: 'Two dies in one package; successor generation.' },
  ],
  strengths: [
    'Very high dense matrix throughput: 989.4 TFLOP/s BF16, 1,979 FP8.',
    '3.35 TB/s HBM3 feeds memory-bound inference.',
    'Scales across 8 GPUs at 900 GB/s each over NVLink.',
  ],
  weaknesses: [
    'Up to 700 W per GPU: power and cooling dominate datacenter design.',
    '80 GB per GPU: large models must be split across GPUs.',
    'Far-L2 accesses and HBM misses cost hundreds of cycles.',
  ],
  course: {
    q: 'A 7-billion-parameter model in FP16 generates one token at batch size 1 on an H100 SXM. Each token reads every weight once. What is the upper bound on tokens per second?',
    steps: [
      'Weights = 7 × 10⁹ × 2 bytes = 14 GB.',
      'Time per token ≥ 14 GB ÷ 3.35 TB/s ≈ 4.2 ms.',
      'Tokens per second ≤ 1 ÷ 0.0042 s ≈ 240.',
    ],
    answer: '≈ 240 tokens/s at best: memory bandwidth, not FLOP/s, is the limit at batch size 1.',
  },
  realWorld: [
    { b: 'Use the smaller number formats (BF16, FP8) when your model allows it.', i: 'BF16/FP8 tensor-core paths (cuBLAS, cuDNN, Transformer Engine) give 2–4× over FP32-class math.' },
    { b: 'Keep data on the GPU; copying over PCIe is slow compared to HBM.', i: 'Host↔device over PCIe 5.0 (~63 GB/s each way) is ~50× slower than HBM3; overlap copies with compute.' },
    { b: 'Libraries use the tile mover (TMA) for you.', i: 'CUTLASS/cuDNN kernels use TMA + warp-specialised pipelines; hand-written kernels rarely beat them.' },
  ],
  compare: {
    type: { value: 'Datacenter AI GPU', src: S.ds },
    process: { value: 'TSMC 4N', src: S.wp },
    packaging: { value: 'GH100 die + 5 HBM3 stacks on CoWoS interposer', src: S.wp },
    compute: { value: '132 SMs · 16,896 FP32 lanes', src: S.ds },
    clock: { value: '≈ 1.98 GHz boost (derived from 67 TFLOP/s ÷ 16,896 lanes ÷ 2)', src: S.ds },
    fp32: { value: '67 TFLOP/s', src: S.ds },
    matrix: { value: 'BF16 989.4 · FP8 1,979 TFLOP/s dense', src: S.ds },
    memory: { value: '80 GB HBM3', src: S.ds },
    bandwidth: { value: '3.35 TB/s', src: S.ds },
    llc: { value: '50 MB L2', src: S.ds },
    power: { value: 'up to 700 W', src: S.ds },
    links: { value: 'NVLink 4 900 GB/s · PCIe 5.0 x16', src: S.ds },
  },
};
