import type { Architecture } from './types';
import { CPU_ZEN4 } from '../chipmaps';

const S = { amd: 'amd', zen4: 'zen4', cnc: 'cnc', jedec: 'jedec', pcisig: 'pcisig', drv: 'drv' } as const;

export const ZEN4_7950X: Architecture = {
  id: 'zen4-7950x', world: 'cpu', group: 'CPU families', family: 'x86 · AMD', name: 'AMD Ryzen 9 7950X (Zen 4)', short: 'Zen 4 · Ryzen 9 7950X', maker: 'AMD', year: 2022, status: 'ready',
  isa: 'x86-64 (with AVX-512)', usedIn: 'Desktops and workstations; the same Zen 4 cores power EPYC "Genoa" servers.',
  tree: CPU_ZEN4, spec: 'ryzen-7950x',
  sources: [
    { id: S.amd, title: 'AMD Ryzen 9 7950X product specifications', year: 2022 },
    { id: S.zen4, title: 'AMD "Zen 4" architecture disclosures, Ryzen 7000 launch', year: 2022 },
    { id: S.cnc, title: 'Chips and Cheese, AMD Zen 4 microarchitecture articles (measurements)', year: 2022 },
    { id: S.jedec, title: 'JEDEC JESD79-5 DDR5 SDRAM standard', year: 2020 },
    { id: S.pcisig, title: 'PCI-SIG, PCI Express Base Specification 5.0', year: 2019 },
    { id: S.drv, title: 'Derived on this site from the sourced core count and core width (see note)', year: 2024 },
  ],
  glance: [
    { label: 'Cores / threads', value: '16 / 32', src: S.amd },
    { label: 'Max boost', value: '5.7 GHz', src: S.amd },
    { label: 'L3', value: '64 MB (2 × 32 MB)', src: S.amd },
    { label: 'Memory', value: 'DDR5-5200, 2 channels', src: S.amd },
    { label: 'TDP', value: '170 W', src: S.amd },
    { label: 'Dies', value: '2 CCDs (TSMC N5) + 1 I/O die (N6)', src: S.zen4 },
  ],
  parts: {
    'cpu.core': { key: { label: 'Cores', value: '16 Zen 4 cores, 2 threads each', src: S.amd } },
    'cpu.bpred': { key: { label: 'BTB', value: 'L1 BTB 1.5K + L2 BTB 7K entries', src: S.zen4 }, note: 'AMD publishes BTB sizes but not the predictor algorithm itself.' },
    'cpu.l1i': { key: { label: 'L1I', value: '32 KB', src: S.zen4 } },
    'cpu.decode': { key: { label: 'Decode', value: '4 instructions/cycle · Op Cache 6.75K ops', src: S.zen4 } },
    'cpu.rename': { key: { label: 'Dispatch', value: '6 macro-ops/cycle', src: S.zen4 } },
    'cpu.rob': { key: { label: 'Retire queue', value: '320 entries', src: S.zen4 } },
    'cpu.sched': { key: { label: 'Integer pipes', value: '4 ALU + 3 AGU', src: S.zen4 } },
    'cpu.prf': { key: { label: 'Registers', value: '224 integer · 192 FP', src: S.zen4 } },
    'cpu.alu': { key: { label: 'ALUs', value: '4', src: S.zen4 } },
    'cpu.lsu': { key: { label: 'Memory ops', value: '3 per cycle (≤ 2 stores)', src: S.zen4 } },
    'cpu.fpsimd': { key: { label: 'Vectors', value: 'AVX-512 on 256-bit datapaths', src: S.zen4 }, note: 'Zen 4 executes 512-bit AVX-512 operations by splitting them across 256-bit units.' },
    'cpu.l1d': { key: { label: 'L1D', value: '32 KB · 8-way · 64 B lines', src: S.zen4 }, note: 'Load-to-use is about 4–5 cycles in measurements (approx.).' },
    'cpu.tlb': { key: { label: 'DTLB', value: 'L1 DTLB 72 · L2 DTLB 3,072 entries', src: S.zen4 } },
    'cpu.l2': { key: { label: 'L2', value: '1 MB per core · 14 cycles', src: S.zen4 } },
    'cpu.l3': { key: { label: 'L3', value: '32 MB per 8-core CCD · ≈ 50 cycles (approx.)', src: S.cnc }, note: 'Each CCD has its own L3; a core can’t hit in the other CCD’s L3 directly.' },
    'cpu.interconnect': { key: { label: 'Fabric', value: 'Infinity Fabric: 2 CCDs ↔ I/O die', src: S.zen4 } },
    'cpu.coherence': { note: 'AMD hasn’t published where every coherence structure sits; drawn schematically in the I/O die.' },
    'cpu.memctl': { key: { label: 'Channels', value: '2 × DDR5 on the I/O die', src: S.amd } },
    'cpu.dram': { key: { label: 'Bandwidth', value: 'DDR5-5200 × 2 channels = 83.2 GB/s peak', src: S.jedec } },
    'cpu.pcie': { key: { label: 'Lanes', value: '28 × PCIe 5.0 (24 usable)', src: S.amd } },
    'cpu.power': { key: { label: 'TDP', value: '170 W', src: S.amd } },
    'cpu.nvme': { key: { label: 'Link', value: 'PCIe 5.0 x4 ≈ 15.8 GB/s each way', src: S.pcisig } },
    'cpu.numa': { note: 'A single-socket desktop: one NUMA node. The two CCDs share one I/O die and memory controller.' },
  },
  diff: [
    { b: '**Chiplets, not one die.** Two 8-core chips and a separate input/output chip share one package.', i: '**Chiplets:** 2 CCDs (cores + L3) and 1 IOD (memory, PCIe) instead of one monolithic die.' },
    { b: '**Two separate L3 caches.** Each 8-core chiplet has its own 32 MB.', i: '**Split L3:** 32 MB per CCD; cross-CCD sharing goes over Infinity Fabric through the IOD.' },
    { b: '**Memory is one hop further.** The memory controller sits on the I/O chip, not next to the cores.', i: '**Off-die IMC:** every DRAM access crosses the fabric to the IOD, adding latency vs an on-die controller.' },
    { b: '**AVX-512 done in halves.** It runs 512-bit vector instructions on 256-bit hardware.', i: '**AVX-512 on 256-bit datapaths:** full ISA support (incl. BF16/VNNI) without doubling the FP units.' },
    { b: '**A 3D-stacked cache version exists.** The X3D models stack extra L3 on top of a chiplet.', i: '**3D V-Cache variants** (e.g. 7950X3D, 2023) stack 64 MB more SRAM on one CCD.' },
  ],
  choices: [
    { title: 'Why chiplets?', text: { b: 'Small chips are cheaper to make without defects, and the same core chiplet can be reused in desktop and server CPUs.', i: 'Smaller dies yield better, and one CCD design serves Ryzen and EPYC. The cost is extra latency and power on the fabric.' } },
    { title: 'Why put I/O on an older process?', text: { b: 'Wires to memory and expansion slots don’t get smaller on new processes, so they stay on a cheaper chip.', i: 'Analog I/O (DDR/PCIe PHYs) scales poorly; N6 for the IOD saves cost while the cores get N5.' } },
    { title: 'Why AVX-512 on 256-bit units?', text: { b: 'It lets programs use the newer instructions without making the core much bigger or hotter.', i: 'ISA compatibility and better instruction efficiency without the area/power of full 512-bit datapaths.' } },
  ],
  timeline: [
    { year: '2017', name: 'Zen', note: 'Return to high-performance x86 cores; 4-core CCX design.' },
    { year: '2019', name: 'Zen 2', note: 'Chiplets arrive: CCDs + separate I/O die.' },
    { year: '2020', name: 'Zen 3', note: 'Unified 8-core complex sharing one L3 per CCD.' },
    { year: '2022', name: 'Zen 4', note: 'AM5, DDR5, PCIe 5.0, AVX-512.', current: true },
    { year: '2024', name: 'Zen 5', note: 'Wider core; successor generation.' },
  ],
  strengths: [
    'High multi-threaded throughput: 16 cores / 32 threads on a desktop socket.',
    'Large total L3 (64 MB) keeps many working sets on-chip.',
    'Modern platform: DDR5 and PCIe 5.0.',
  ],
  weaknesses: [
    'Threads that share data across the two CCDs pay extra latency.',
    'DRAM latency includes a fabric hop to the I/O die.',
    'Two memory channels (83.2 GB/s peak) limit bandwidth-heavy work.',
  ],
  course: {
    q: 'A program streams through 4 GB of data once on a Ryzen 9 7950X with DDR5-5200 in both channels. What is the shortest possible time, and why is real code slower?',
    steps: [
      'Peak bandwidth = 2 channels × 8 bytes × 5,200 MT/s = 83.2 GB/s.',
      'Time ≥ 4 GB ÷ 83.2 GB/s ≈ 0.048 s ≈ 48 ms.',
      'Real code reaches only part of the peak: refresh, bank conflicts and read/write turnarounds cost bandwidth.',
    ],
    answer: '≈ 48 ms lower bound; real runs are slower because sustained DRAM bandwidth is below peak.',
  },
  realWorld: [
    { b: 'Keep threads that share data on the same 8-core chiplet when you can.', i: 'Pin communicating threads to one CCD (e.g. with taskset or a thread pool’s affinity) to avoid cross-CCD fabric traffic.' },
    { b: 'Programs that read huge amounts of memory are limited by RAM speed, not by the cores.', i: 'Memory-bound kernels top out near 83.2 GB/s peak; block for L2/L3 reuse instead of adding threads.' },
    { b: 'Software built for newer vector instructions can run faster here.', i: 'Build with AVX-512 enabled (e.g. -march=znver4) when your compiler supports it, and measure; gains vary by workload.' },
  ],
  compare: {
    type: { value: 'Desktop CPU · x86-64', src: S.amd },
    process: { value: 'CCD: TSMC N5 · IOD: N6', src: S.zen4 },
    packaging: { value: '2 CCD chiplets + 1 I/O die', src: S.zen4 },
    compute: { value: '16 cores / 32 threads', src: S.amd },
    clock: { value: 'up to 5.7 GHz', src: S.amd },
    fp32: { value: '≈ 2.56 TFLOP/s (derived: 16 cores × 32 FLOP/cycle × 5.0 GHz assumed all-core)', src: S.drv },
    matrix: { value: 'No matrix unit; AVX-512 incl. BF16 and VNNI', src: S.zen4 },
    memory: { value: 'DDR5-5200, 2 channels', src: S.amd },
    bandwidth: { value: '83.2 GB/s peak', src: S.jedec },
    llc: { value: '64 MB L3 (2 × 32 MB)', src: S.amd },
    power: { value: '170 W TDP', src: S.amd },
    links: { value: '28 × PCIe 5.0 (24 usable)', src: S.amd },
  },
};
