import type { MapComponent } from './types';

// Every clickable part on every map. Key numbers ("num") describe the map's
// reference chip: AMD Zen 4 / Ryzen 9 7950X for the CPU world, NVIDIA H100 SXM5
// (in a DGX H100 server) for the GPU world.

const C = (c: MapComponent) => c;

export const COMPONENTS: MapComponent[] = [
  // ---------------- Foundations ----------------
  C({ id: 'found.transistor', world: 'foundations', zone: 'found', kind: 'neutral', tech: 'Transistors & bits', friendly: 'Tiny switches', hover: 'A transistor is a switch that electricity can flip. One switch = one bit.', teaser: 'Everything starts with a switch that is on or off.' }),
  C({ id: 'found.gates', world: 'foundations', zone: 'found', kind: 'neutral', tech: 'Gates → adder → ALU', friendly: 'Switches that do math', hover: 'Wire switches together and they can add.', teaser: 'From AND/OR to a circuit that adds two numbers.' }),
  C({ id: 'found.clock', world: 'foundations', zone: 'found', kind: 'cpu', tech: 'Clock', friendly: 'The heartbeat', hover: '3 GHz = 3 billion ticks per second.', teaser: 'What "3 GHz" actually counts.' }),
  C({ id: 'found.numbers', world: 'foundations', zone: 'found', kind: 'math', tech: 'Number formats', friendly: 'How numbers are stored', hover: 'Integers, FP32, FP16, BF16, FP8: same bits, different trade-offs.', teaser: 'Why AI uses 16-bit and 8-bit numbers.' }),

  // ---------------- CPU world: inside a core ----------------
  C({ id: 'cpu.frontend', world: 'cpu', zone: 'core', kind: 'cpu', tech: 'Front end (fetch)', friendly: 'Instruction fetcher', num: 'L1I 32 KB', hover: { b: 'Grabs the next instructions of your program.', i: 'Fetches instruction bytes from the L1I cache each cycle, steered by the branch predictor.' }, teaser: 'Where every instruction enters the core.' }),
  C({ id: 'cpu.bpred', world: 'cpu', zone: 'core', kind: 'cpu', tech: 'Branch predictor', friendly: 'The guesser', num: 'BTB 1.5K + 7K entries', hover: { b: 'Guesses which way each "if" will go, so the core never waits to find out.', i: 'Predicts direction and target of branches; a misprediction flushes the pipeline.' }, teaser: 'Guessing the future, correctly most of the time.' }),
  C({ id: 'cpu.decode', world: 'cpu', zone: 'core', kind: 'cpu', tech: 'Decode', friendly: 'Translator', num: '4-wide x86 decode', hover: { b: 'Turns instruction bytes into simple steps the core can run.', i: 'Decodes x86 instructions into micro-ops; an op cache skips decode for hot code.' }, teaser: 'x86, ARM, RISC‑V: different languages, same idea.' }),
  C({ id: 'cpu.rob', world: 'cpu', zone: 'core', kind: 'cpu', tech: 'Rename / reorder buffer', friendly: 'Out-of-order bookkeeping', num: '320-entry ROB', hover: { b: 'Lets the core do work out of order, then puts results back in order.', i: 'Renames registers to remove false dependences; the ROB retires micro-ops in program order.' }, teaser: 'Doing things out of order without anyone noticing.' }),
  C({ id: 'cpu.sched', world: 'cpu', zone: 'core', kind: 'cpu', tech: 'Schedulers', friendly: 'The dispatcher', num: '6 ops dispatched / cycle', hover: { b: 'Sends each step to a free worker as soon as its inputs are ready.', i: 'Reservation stations hold micro-ops until operands are ready, then issue them.' }, teaser: 'Who runs next, and when.' }),
  C({ id: 'cpu.alu', world: 'cpu', zone: 'core', kind: 'gpu', tech: 'Integer ALUs', friendly: 'Integer math', num: '4 ALUs', hover: { b: 'Adds, compares and shifts whole numbers.', i: 'Single-cycle integer ops; results forward straight to dependent instructions.' }, teaser: 'Where whole-number math happens.' }),
  C({ id: 'cpu.fpu', world: 'cpu', zone: 'core', kind: 'gpu', tech: 'FP units', friendly: 'Decimal math', num: '2 × 256-bit FMA', hover: { b: 'Math on numbers with decimal points.', i: 'Floating-point add/multiply/FMA pipelines, shared with the vector units.' }, teaser: 'Floating-point math, a few cycles per result.' }),
  C({ id: 'cpu.lsu', world: 'cpu', zone: 'core', kind: 'mem', tech: 'Load / store', friendly: 'Memory doorway', num: '3 mem ops / cycle', hover: { b: 'Reads data from memory into the core and writes it back.', i: 'Computes addresses, checks the TLB, and talks to the L1 data cache.' }, teaser: 'Every read and write passes through here.' }),
  C({ id: 'cpu.simd', world: 'cpu', zone: 'core', kind: 'gpu', tech: 'SIMD / vector', friendly: 'Batch math', num: 'AVX-512 (2 × 256)', hover: { b: 'One instruction that does the same math on many numbers at once.', i: 'SSE/AVX/NEON: one instruction, 4–16 lanes of data.' }, teaser: 'A tiny taste of GPU-style math inside a CPU.' }),
  C({ id: 'cpu.regs', world: 'cpu', zone: 'core', kind: 'mem', tech: 'Register file', friendly: 'The core’s notepad', num: '16 x86-64 GPRs', hover: { b: 'A handful of the fastest storage slots, right inside the core.', i: 'Architectural registers map onto a larger physical register file.' }, teaser: 'Storage that answers in a single cycle.' }),

  // ---------------- CPU world: memory ----------------
  C({ id: 'cpu.l1i', world: 'cpu', zone: 'memory', kind: 'mem', tech: 'L1 instruction cache', friendly: 'Instruction shelf', num: '32 KB', hover: { b: 'Keeps the program’s next instructions close by.', i: 'Private per core, read by the front end every cycle.' }, teaser: 'Instructions need caching too.' }),
  C({ id: 'cpu.l1d', world: 'cpu', zone: 'memory', kind: 'mem', tech: 'L1 data cache', friendly: 'The closest shelf', num: '32 KB · 8-way · ~4–5 cyc', hover: { b: 'A small, very fast store of recently used data, right next to the core.', i: '32 KB, 8-way, 64 B lines, ~4–5 cycles to use (approx.).' }, teaser: { b: 'The 32 KB that does most of the work.', i: '32 KB, 8 ways, 64 sets: how an address finds its byte.' }, sandbox: { label: 'Open in cache simulator', href: '#/lab/cache' } }),
  C({ id: 'cpu.l2', world: 'cpu', zone: 'memory', kind: 'mem', tech: 'L2 cache', friendly: 'The nearby cupboard', num: '1 MB · ~14 cyc', hover: { b: 'Bigger and a bit slower than L1. Catches what L1 drops.', i: '1 MB private per core, ~14 cycles (approx.).' }, teaser: 'The second chance before things get slow.', sandbox: { label: 'Open in cache simulator', href: '#/lab/cache' } }),
  C({ id: 'cpu.l3', world: 'cpu', zone: 'memory', kind: 'mem', tech: 'L3 cache', friendly: 'The shared pantry', num: '32 MB per 8 cores', hover: { b: 'A big store shared by all the cores on the chip.', i: 'Shared victim cache per chiplet, ~50 cycles (approx.).' }, teaser: 'Shared by every core, and how they keep it consistent.' }),
  C({ id: 'cpu.memctl', world: 'cpu', zone: 'memory', kind: 'mem', tech: 'Memory controller', friendly: 'RAM traffic control', num: '2 × DDR5 channels', hover: { b: 'Schedules every trip out to the RAM sticks.', i: 'Schedules DRAM commands across channels, ranks and banks.' }, teaser: 'Turning requests into DRAM commands.' }),
  C({ id: 'cpu.dram', world: 'cpu', zone: 'memory', kind: 'mem', tech: 'DRAM', friendly: 'Main memory (RAM)', num: '83.2 GB/s · ~80–100 ns', hover: { b: 'Gigabytes of storage, but far away: hundreds of cycles per trip.', i: 'DDR5-5200 × 2 channels = 83.2 GB/s; ~80–100 ns latency (approx.).' }, teaser: 'Huge, cheap, and slow to reach.' }),
  C({ id: 'cpu.tlb', world: 'cpu', zone: 'memory', kind: 'mem', tech: 'TLB & page tables', friendly: 'Address translator', num: '4 KB pages', hover: { b: 'Translates the addresses programs use into real memory locations.', i: 'Caches virtual→physical translations; a miss walks the page table.' }, teaser: 'Every program thinks it owns all the memory.' }),

  // ---------------- CPU world: chip ----------------
  C({ id: 'cpu.cores', world: 'cpu', zone: 'chip', kind: 'cpu', tech: 'Multicore', friendly: 'Many cores', num: '16 cores / 32 threads', hover: { b: 'Several complete cores on one chip.', i: '2 chiplets × 8 Zen 4 cores, plus an I/O die.' }, teaser: 'More cores help only if the work splits (Amdahl’s law).' }),
  C({ id: 'cpu.fabric', world: 'cpu', zone: 'chip', kind: 'mem', tech: 'Interconnect', friendly: 'On-chip roads', num: '2 CCDs + I/O die', hover: { b: 'The wiring that carries data between cores, caches and memory.', i: 'Infinity Fabric links the core chiplets to the I/O die.' }, teaser: 'Rings, meshes and chiplets.' }),
  C({ id: 'cpu.coherence', world: 'cpu', zone: 'chip', kind: 'mem', tech: 'Cache coherence (MESI)', friendly: 'Keeping copies in sync', num: '64 B granularity', hover: { b: 'Makes sure two cores never see different values for the same data.', i: 'MESI states per 64 B line; false sharing ping-pongs lines between cores.' }, teaser: 'Why two threads touching neighbouring bytes can be slow.' }),
  C({ id: 'cpu.power', world: 'cpu', zone: 'chip', kind: 'cpu', tech: 'Power & heat', friendly: 'Why chips get hot', num: '170 W TDP', hover: { b: 'Every switch flip costs energy, and the heat has to go somewhere.', i: 'Dynamic power ≈ C·V²·f; the end of Dennard scaling capped clocks.' }, teaser: 'Why clock speeds stopped rising around 2005.' }),

  // ---------------- CPU world: motherboard ----------------
  C({ id: 'cpu.pcie', world: 'cpu', zone: 'board', kind: 'mem', tech: 'PCIe lanes', friendly: 'Expansion highway', num: 'Gen5 x16 ≈ 63 GB/s each way', hover: { b: 'High-speed lanes to graphics cards and SSDs.', i: 'Gen5: 3.94 GB/s per lane per direction (after encoding).' }, teaser: 'Lanes, generations and real bandwidth.' }),
  C({ id: 'cpu.nvme', world: 'cpu', zone: 'board', kind: 'mem', tech: 'NVMe SSD', friendly: 'Storage drive', num: 'Gen4 x4 link ≈ 7.9 GB/s', hover: { b: 'Where files live when the power is off.', i: 'Flash storage over 4 PCIe lanes; deep queues hide latency.' }, teaser: 'Fast storage is still ~1000× slower than RAM.' }),
  C({ id: 'cpu.numa', world: 'cpu', zone: 'board', kind: 'mem', tech: 'NUMA', friendly: 'Near and far memory', num: '1 node desktop · 2+ servers', hover: { b: 'On big servers, some memory is closer to some cores.', i: 'Non-uniform memory access: remote-socket memory costs extra latency.' }, teaser: 'When "memory" has a location.' }),
  C({ id: 'cpu.gpulink', world: 'cpu', zone: 'board', kind: 'mem', tech: 'Link to the GPU', friendly: 'Road to the GPU', num: 'PCIe 4.0 x16 ≈ 31.5 GB/s', hover: { b: 'The cable-free road the CPU uses to hand work to a graphics card.', i: 'Host↔device copies over PCIe; often the hidden bottleneck.' }, teaser: 'Cross the bridge to the GPU world.' }),

  // ---------------- GPU world: chip ----------------
  C({ id: 'gpu.sms', world: 'gpu', zone: 'chip', kind: 'gpu', tech: 'Streaming multiprocessors', friendly: 'Worker units', num: '132 of 144 SMs on', hover: { b: 'Each one is a mini-processor running thousands of threads.', i: '132 enabled SMs on H100 SXM, each with 128 FP32 lanes and 4 tensor cores.' }, teaser: { b: 'Where all the GPU’s work happens.', i: 'Threads, warps, blocks, grids: how work lands on 132 SMs.' } }),
  C({ id: 'gpu.l2', world: 'gpu', zone: 'chip', kind: 'mem', tech: 'L2 cache', friendly: 'The shared middle store', num: '50 MB', hover: { b: 'A big store in the middle that all workers share.', i: '50 MB, split in two partitions; every HBM access goes through it.' }, teaser: 'The GPU’s last stop before HBM.' }),
  C({ id: 'gpu.hbm', world: 'gpu', zone: 'chip', kind: 'mem', tech: 'HBM3 stacks', friendly: 'Stacked memory', num: '5 stacks · 3.35 TB/s · 80 GB', hover: { b: 'Memory chips piled up right next to the GPU, with a very wide connection.', i: '1024-bit interface per stack; 3.35 TB/s total on H100 SXM.' }, teaser: 'Why GPU memory is 40× faster than your RAM.' }),
  C({ id: 'gpu.blocksched', world: 'gpu', zone: 'chip', kind: 'cpu', tech: 'Block scheduler', friendly: 'Work handout desk', num: '≤ 32 blocks per SM', hover: { b: 'Hands out chunks of work (blocks) to free SMs.', i: 'Distributes thread blocks to SMs as resources free up.' }, teaser: 'Who decides which SM gets which block.' }),
  C({ id: 'gpu.copy', world: 'gpu', zone: 'chip', kind: 'mem', tech: 'Copy engines / PCIe', friendly: 'Loading dock', num: 'PCIe 5.0 x16 ≈ 63 GB/s', hover: { b: 'Where data arrives from the CPU.', i: 'DMA copy engines move data host↔device while SMs compute.' }, teaser: 'Data has to get here first.' }),

  // ---------------- GPU world: inside an SM ----------------
  C({ id: 'gpu.warpsched', world: 'gpu', zone: 'sm', kind: 'cpu', tech: 'Warp schedulers', friendly: 'Turn-takers', num: '4 per SM · 1 warp-instr/cycle each', hover: { b: 'Each cycle, picks a group of 32 threads that is ready and lets it run.', i: 'Issues one instruction per cycle from a ready warp; switching is free.' }, teaser: 'How a GPU hides waiting.' }),
  C({ id: 'gpu.fp32', world: 'gpu', zone: 'sm', kind: 'gpu', tech: 'FP32 lanes ("CUDA cores")', friendly: 'Math lanes', num: '128 per SM', hover: { b: 'Simple math units. A GPU has thousands.', i: '32 lanes per partition; one warp instruction = 32 lanes in lockstep.' }, teaser: '16,896 lanes doing simple math together.' }),
  C({ id: 'gpu.tensor', world: 'gpu', zone: 'sm', kind: 'gpu', tech: 'Tensor cores', friendly: 'Matrix engines', num: '4 per SM', hover: { b: 'Special units that multiply small grids of numbers in one go.', i: 'Matrix-multiply-accumulate on tiles; most of the GPU’s FLOP/s.' }, teaser: 'Where AI’s math actually happens.' }),
  C({ id: 'gpu.regfile', world: 'gpu', zone: 'sm', kind: 'mem', tech: 'Register file', friendly: 'Every thread’s notepad', num: '256 KB per SM', hover: { b: 'Huge: every thread keeps its own values here, so switching costs nothing.', i: '64K × 32-bit registers per SM; bigger than the L1 of most CPUs.' }, teaser: 'Why a GPU’s registers outweigh its caches.' }),
  C({ id: 'gpu.smem', world: 'gpu', zone: 'sm', kind: 'mem', tech: 'Shared memory / L1', friendly: 'Team scratchpad', num: '256 KB (≤ 228 KB shared)', hover: { b: 'A fast scratchpad that threads in the same block share.', i: '32 banks × 4 B; configurable split between L1 and shared memory.' }, teaser: 'Banks, conflicts and coalescing.' }),

  // ---------------- GPU world: server ----------------
  C({ id: 'gpu.gpus', world: 'gpu', zone: 'server', kind: 'gpu', tech: '8 × H100 SXM', friendly: 'Eight GPUs', num: '8 GPUs (DGX H100)', hover: { b: 'One server, eight GPUs working on one model.', i: 'DGX H100: 8 × H100 SXM5, 640 GB HBM3 total.' }, teaser: 'Why big models need many GPUs.' }),
  C({ id: 'gpu.nvswitch', world: 'gpu', zone: 'server', kind: 'mem', tech: 'NVLink & NVSwitch', friendly: 'GPU-to-GPU highway', num: '900 GB/s per GPU', hover: { b: 'A private, very fast road so GPUs can share data directly.', i: 'NVLink 4: 900 GB/s per GPU total, through 4 NVSwitch chips.' }, teaser: 'All-to-all at 900 GB/s.' }),
  C({ id: 'gpu.nics', world: 'gpu', zone: 'server', kind: 'mem', tech: 'NICs & network', friendly: 'Link to other servers', num: '8 × 400 Gb/s', hover: { b: 'Connects this server to thousands of others.', i: 'ConnectX-7 400 Gb/s per GPU for the compute fabric.' }, teaser: 'Scaling past one box.' }),
  C({ id: 'gpu.host', world: 'gpu', zone: 'server', kind: 'cpu', tech: 'Host CPUs', friendly: 'The CPUs in charge', num: '2 CPUs', hover: { b: 'CPUs that run the program and feed the GPUs.', i: 'Launch kernels, run the data pipeline, copy batches over PCIe.' }, teaser: 'The CPU’s job in a GPU server.' }),

  // ---------------- Bridge stations ----------------
  C({ id: 'bridge.why', world: 'bridge', zone: 'cpuvgpu', kind: 'neutral', tech: 'Latency vs throughput', friendly: 'Why GPUs exist', hover: 'Same job, two machines: a race.', teaser: { b: 'A race on the same job: who wins, and why?', i: 'Sum 100 M floats and a 4096² matmul on a CPU and a GPU.' } }),
  C({ id: 'bridge.side', world: 'bridge', zone: 'cpuvgpu', kind: 'neutral', tech: 'Side by side', friendly: 'Same workload, both machines', hover: 'Three workloads, two machines.', teaser: 'Array sum, matmul and a branchy loop.' }),
  C({ id: 'bridge.branch', world: 'bridge', zone: 'cpuvgpu', kind: 'neutral', tech: 'Prediction vs divergence', friendly: 'Handling "if"', hover: 'CPUs guess; GPUs split warps.', teaser: 'Branch prediction vs warp divergence.' }),
  C({ id: 'bridge.caches', world: 'bridge', zone: 'cpuvgpu', kind: 'neutral', tech: 'Caches vs register files', friendly: 'Where the silicon goes', hover: 'Big caches vs huge register files.', teaser: 'Two ways to spend a transistor budget.' }),
  C({ id: 'bridge.pcie', world: 'bridge', zone: 'cpuvgpu', kind: 'neutral', tech: 'Feeding the GPU', friendly: 'CPU → GPU over PCIe', hover: 'The copy before the compute.', teaser: 'Why the copy can cost more than the math.' }),
  C({ id: 'bridge.roofline', world: 'bridge', zone: 'ai', kind: 'math', tech: 'Roofline model', friendly: 'Compute or memory?', hover: 'One chart that says what limits a program.', teaser: 'attainable = min(peak, intensity × bandwidth)' }),
  C({ id: 'bridge.matmul', world: 'bridge', zone: 'ai', kind: 'neutral', tech: 'Matmul vs attention', friendly: 'Why some AI math is slow', hover: 'Compute-bound vs memory-bound.', teaser: 'Same GPU, very different speeds.' }),
  C({ id: 'bridge.precision', world: 'bridge', zone: 'ai', kind: 'math', tech: 'Mixed precision', friendly: 'Smaller numbers, faster AI', hover: 'FP32 → BF16 → FP8.', teaser: 'Fewer bits, more math per second.' }),
  C({ id: 'bridge.layer', world: 'bridge', zone: 'ai', kind: 'neutral', tech: 'One transformer layer', friendly: 'Where the time goes', hover: 'A time breakdown of one layer.', teaser: 'Matmuls, attention, and waiting.' }),
];

export const component = (id: string) => COMPONENTS.find(c => c.id === id);
